title: Yay for GitHub Pages
author: mboyce
email: mboyce@rti.org
description: > # this means to ignore newlines until "baseurl:"
  This is a page that's going to look awesome!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
